name: Nullstone
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Package lambda code
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install node lambda dependencies
        working-directory: db-admin
        run: npm install
      - name: Package lambda code
        run: zip -r ./db-admin.zip ./db-admin

      # Package files into tgz
      - name: Package
        run: tar -cvzf module.tgz *.tf db-admin.zip

      - name: Find version
        id: version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}

      # Publish to nullstone
      - name: Publish
        env:
          NULLSTONE_ORG: nullstone
          NULLSTONE_MODULE: aws-rds-postgres
          RELEASE_VERSION: ${{ steps.version.outputs.tag }}
        run: |-
          curl -XPOST -F "file=@module.tgz" -H "X-Nullstone-Key: ${{ secrets.NULLSTONE_API_KEY }}" \
            https://api.nullstone.io/orgs/${NULLSTONE_ORG}/modules/${NULLSTONE_MODULE}/versions?version=${RELEASE_VERSION}
